### ISSUE TITLE
Unable to create bot

### ISSUE THREAD

**Issue by dingyufei615** [poe-platform/api-bot-tutorial#16]
<img width="888" alt="image" src="https://github.com/poe-platform/api-bot-tutorial/assets/34468774/aff33ab0-9002-48ad-bd72-baf242d78256">

<img width="986" alt="image" src="https://github.com/poe-platform/api-bot-tutorial/assets/34468774/dedb575b-388e-4bee-a9e6-eb83d0d4bdf4">

**Comment by JelleZijlstra** [comment]
Could you share your Poe handle (like https://poe.com/jelle for me)? That should make it easier for us to find out what the error is.

**Comment by dingyufei615** [comment]
> Could you share your Poe handle (like https://poe.com/jelle for me)? That should make it easier for us to find out what the error is.你能分享你的 Poe 句柄吗（比如我的 https://poe.com/jelle ）？这应该使我们更容易找出错误是什么。
thanks,this my  Poe handle
https://poe.com/exaa

**Comment by JelleZijlstra** [comment]
Thanks! The issue is that we require the API URL to be HTTPS. We should check this on the frontend too; sorry for missing that.

**Comment by dingyufei615** [comment]
> Thanks! The issue is that we require the API URL to be HTTPS. We should check this on the frontend too; sorry for missing that.

>Thanks sir,i'll update my server to suport HTTPS

**Comment by takeraparterer** [comment]
How would I configure it to use https? please help :)

**Comment by JelleZijlstra** [comment]
Use an https URL when creating the bot. If you use a service like Modal to host your bot, it should automatically support https.
