### ISSUE TITLE
Bot request fail on try

### ISSUE THREAD

**Issue by JohnPham69** [poe-platform/api-bot-tutorial#32]
So, I tried to run the bot right on my console, by adding these codes into the main.py:

```
async def run(the_content):
    query = QueryRequest(
        version="1.0",
        type="query",
        query=[
            {
                "content": the_content,
                "message_id": "123",
                "role": "user",
                "content_type": "text/markdown"
                }
               ],
        user_id="u-ser123",
        conversation_id="c-onversation123",
        message_id="m-essage123",
        api_key = "MCSXqhvQATRgXiRWkIB025gPkPMuu84q"
    )    
    response = bot.get_response(query)
    async for event in response:
        print(event.data)
if __name__ == "__main__":
    content = input("something: ")
    asyncio.run(run(content))
```
Which the EchoBot, HuggingFaceBot worked perfectly. But when I uncommented the 
bot = ChatGPTAllCapsBot(), and ran the code, the console poped me this error:

![image](https://github.com/poe-platform/api-bot-tutorial/assets/122061569/e44cb771-35cd-47bf-8a7c-7c3cf951964e)

Compare to what I get when run the EchoBot:
![image](https://github.com/poe-platform/api-bot-tutorial/assets/122061569/40a9f6ae-388e-4c67-831f-94024b2797d0)

Please help, I don't know how to run the chatGPT bot so it would look like the Echo one

**Comment by JelleZijlstra** [comment]
You can only talk to other Poe bots from the context of a Poe request. You'll have to create a bot in Poe (poe.com/create_bot?api=1), then communicate with it through the Poe client.
